# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  spring_server:
    depends_on:
      - mongo_db
    build:
      context: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
        }'
  mongo_db:
      image: mongo
      restart: no
      env_file: ./.env
      environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
        - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      ports:
        - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
      volumes:
        - db:/data/db
volumes:
  db: